Updated for compatibility with latest version of Flask
Compatibility with Flask 2.2.x required two changes:

1. `flask.views.MethodViewType` is now an import error, so I it has been been
	replaced with `type(MethodView)`

2. Tests were failing with the error:
   ```
   AssertionError: The setup method 'register_blueprint' can no longer be called
   on the application. It has already handled its first request, any changes
   will not be applied consistently.
   ```
   this was solved by changing the 'scope' of the tests so we always have a new
   Flask app instance for each test.